import React, {Component} from 'react'
import {Route, Link, Switch, Redirect, withRouter} from 'react-router-dom'
import {connect} from 'react-redux'
import {browseArtwork} from '../store'
import Artwork from './artwork'
import Artists from './artists'
import NewPiece from './newPiece'
import NewArtist from './newArtist'
import NewLocation from './newLocation'
import Nav from './nav'
import Footer from './footer'
import MapView from './mapView'
import Locations from './locations'
