export default {
    BROWSE_ARTWORK: 'BROWSE_ARTWORK',
    ADD_PIECE: 'ADD_PIECE',
    READ_PIECE: 'READ_PIECE',
    EDIT_PIECE: 'EDIT_PIECE',
    DELETE_PIECE: 'DELETE_PIECE',
    BROWSE_ARTISTS: 'BROWSE_ARTISTS',
    ADD_ARTIST: 'ADD_ARTIST',
    READ_ARTIST: 'READ_ARTIST',
    EDIT_ARTIST: 'EDIT_ARTIST',
    DELETE_ARTIST: 'DELETE_ARTIST',
    CLEAR_SELECTION: 'CLEAR_SELECTION',
    ADD_LOCATION: 'ADD_LOCATION',
    BROWSE_LOCATIONS: 'BROWSE_LOCATIONS'
}
